// Generated by ego.
// DO NOT EDIT

package tasks

import (
	"fmt"
	"github.com/medcl/gopa/modules/ui/templates/common"
	"io"
)

var _ = fmt.Sprint("") // just so that we can keep the fmt import for now
func Index(w io.Writer) error {
	_, _ = io.WriteString(w, "\n\n")
	_, _ = io.WriteString(w, "\n\n")
	common.Head(w, "Tasks", "")
	_, _ = io.WriteString(w, "\n<link rel=\"stylesheet\" href=\"/static/assets/css/tasks.css\" />\n<script src=\"/static/assets/js/jquery.timeago.js\"></script>\n<script src=\"/static/assets/js/page/tasks.js\"></script>\n\n")
	common.Body(w)
	_, _ = io.WriteString(w, "\n")
	common.Nav(w, "Tasks")
	_, _ = io.WriteString(w, "\n\n\n\n<div class=\"tm-middle\">\n\n    <div class=\"uk-container uk-container-center\">\n\n        <div class=\"uk-grid\" data-uk-grid-margin>\n\n\n            <div class=\"uk-width-2-10\">\n                <div class=\"uk-alert\" ><span id=\"domain-alert\"></span></div>\n                <ul id=\"domain-records\" class=\"uk-list\">\n                    <li>...</li>\n                    <li>...</li>\n                    <li>...</li>\n                </ul>\n            </div>\n\n            <div class=\"uk-width-8-10\">\n                <div class=\"uk-alert\" ><span id=\"alert\"></span></div>\n\n                <table id=\"tasks\" class=\"uk-table uk-table-hover uk-table-striped\" cellspacing=\"0\" width=\"100%\">\n                    <thead>\n                    <tr>\n                        <th>ID</th>\n                        <th>Path</th>\n                        <th>Title</th>\n                        <th>Size</th>\n                        <th>Updated</th>\n                    </tr>\n                    </thead>\n                    <tbody id=\"records\">\n                    </tbody>\n                </table>\n\n                <ul class=\"uk-pagination\" data-uk-pagination=\"{items:100, itemsOnPage:10}\"></ul>\n\n            </div>\n        </div>\n\n    </div>\n\n</div>\n\n")
	common.OffCanvas(w)
	_, _ = io.WriteString(w, "\n\n")
	common.Footer(w)
	_, _ = io.WriteString(w, "\n")
	return nil
}
