// Generated by ego.
// DO NOT EDIT

package common

import (
	"fmt"
	"github.com/infinitbyte/gopa/core/env"
	"html"
	"io"
)

var _ = fmt.Sprint("") // just so that we can keep the fmt import for now
func Copyright(w io.Writer, config *UIConfig) error {
	_, _ = io.WriteString(w, "\n")
	_, _ = io.WriteString(w, "\n")
	_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(config.SiteName)))
	_, _ = io.WriteString(w, " ©2017, Powered by <a target=\"_blank\" href=\"https://github.com/infinitbyte/gopa\" >Gopa</a> v")
	_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(env.VERSION)))
	_, _ = io.WriteString(w, " #<a title=\"")
	_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(env.GetLastCommitLog())))
	_, _ = io.WriteString(w, "\" href=\"https://github.com/infinitbyte/gopa/commit/")
	_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(env.GetLastCommitHash())))
	_, _ = io.WriteString(w, "\">")
	_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(env.GetLastCommitHash())))
	_, _ = io.WriteString(w, "</a>.\n")
	return nil
}
